//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dual_Hotel_EX3.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Habitacio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Habitacio()
        {
            this.Ocupacios = new HashSet<Ocupacio>();
        }
    
        public int Numero { get; set; }
        public byte TeTerrassa { get; set; }
        public byte EsUtilitzable { get; set; }
        public decimal M2 { get; set; }
        public int TipusHabitacio { get; set; }
        public int NumPlanta { get; set; }
    
        public virtual Planta Planta { get; set; }
        public virtual TipusHabitacio TipusHabitacio1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ocupacio> Ocupacios { get; set; }
    }
}
