//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dual_Hotel_EX3.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class hotelEntities : DbContext
    {
        public hotelEntities()
            : base("name=hotelEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<Habitacio> Habitacios { get; set; }
        public virtual DbSet<Hoste> Hostes { get; set; }
        public virtual DbSet<Ocupacio> Ocupacios { get; set; }
        public virtual DbSet<Pensio> Pensios { get; set; }
        public virtual DbSet<Planta> Plantas { get; set; }
        public virtual DbSet<Reserva> Reservas { get; set; }
        public virtual DbSet<Servei> Serveis { get; set; }
        public virtual DbSet<Temporada> Temporadas { get; set; }
        public virtual DbSet<TipusHabitacio> TipusHabitacios { get; set; }
        public virtual DbSet<Reserva_Has_Tipus_Habitacio> Reserva_Has_Tipus_Habitacio { get; set; }
    }
}
