//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dual_Hotel_EX3.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reserva_Has_Tipus_Habitacio
    {
        public int IDReserva { get; set; }
        public int IDTipus { get; set; }
        public int Quantitat { get; set; }
    
        public virtual Reserva Reserva { get; set; }
        public virtual TipusHabitacio TipusHabitacio { get; set; }
    }
}
